name: ${COMPOSE_PROJECT_NAME:-villa-admin-prod}

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${HOST_PORT:-4000}:${PORT:-4000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-4000}
