services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-prod
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production